import mongoose, { Document, Schema } from 'mongoose';

// ──────────────────────────────────────
// SCHEME CHUNK MODEL
//
// This is where the MAGIC of RAG happens
// Each chunk = a small piece of the PDF + its embedding vector
//
// WHAT'S STORED:
// 1. chunkText     → The actual text from the PDF piece
// 2. embedding     → Array of 768 numbers representing meaning
// 3. metadata      → Where in the PDF this text came from
//
// WHY 768 NUMBERS?
// Google's text-embedding-004 model outputs 768 dimensions
// Each dimension captures some aspect of meaning
// Together, they create a "fingerprint" of the text's meaning
//
// HOW SEARCH WORKS:
// 1. User asks: "Am I eligible for PM-KISAN?"
// 2. We convert this question → 768 numbers (query embedding)
// 3. We compare query embedding with ALL stored embeddings
// 4. Find the CLOSEST matches (most similar meaning)
// 5. Those chunks contain the relevant eligibility rules!
//
// This comparison is called COSINE SIMILARITY
// cos(θ) = 1.0 → identical meaning
// cos(θ) = 0.0 → completely unrelated
// cos(θ) = 0.8+ → very relevant (we want these!)
//
// RELATIONSHIP:
// Many SchemeChunks → One Scheme (N:1)
// SchemeChunk.schemeId → Scheme._id
//
// SCALE:
// A 50-page PDF → ~30-40 chunks
// Each chunk → ~500-800 tokens of text + 768 floats
// 5 schemes → ~150-200 chunks total
// ──────────────────────────────────────

export interface ISchemeChunkMetadata {
    pageNumber: number;
    sectionTitle: string;
    paragraph?: number;
}

export interface ISchemeChunk extends Document {
    _id: mongoose.Types.ObjectId;
    schemeId: mongoose.Types.ObjectId;
    chunkText: string;
    chunkIndex: number;
    metadata: ISchemeChunkMetadata;
    embedding: number[];
    createdAt: Date;
}

const schemeChunkSchema = new Schema<ISchemeChunk>(
    {
        // ── schemeId: Which scheme this chunk belongs to ──
        // Links back to the Scheme document
        // When we search, we filter by schemeId to only search
        // chunks from the relevant scheme
        //
        // Example query:
        // "Find chunks from PM-KISAN that mention eligibility"
        // → filter: { schemeId: pmKisanId }
        schemeId: {
            type: Schema.Types.ObjectId,
            ref: 'Scheme',
            required: [true, 'Scheme ID is required'],
            index: true,
        },

        // ── chunkText: The actual text content ──
        //
        // Example:
        // "4.1 Eligibility Criteria
        //  All landholding farmer families with cultivable land
        //  as per land records of the respective State/UT are
        //  eligible for the scheme. The farmer families holding
        //  less than 2 hectares of cultivable land shall be
        //  eligible under the scheme."
        //
        // This is what gets shown as CITATION in proof cards:
        // "Page 4, Section 4.1: 'All landholding farmer families...'"
        chunkText: {
            type: String,
            required: [true, 'Chunk text is required'],
        },

        // ── chunkIndex: Order of this chunk in the document ──
        // Chunk 0 = first chunk (beginning of PDF)
        // Chunk 34 = last chunk (end of PDF)
        // Useful for maintaining document order
        chunkIndex: {
            type: Number,
            required: true,
        },

        // ── metadata: WHERE in the PDF this text came from ──
        //
        // This is CRITICAL for citations
        // When AI says "you're eligible", we need to PROVE it
        // Metadata lets us say:
        // "Based on Page 4, Section 4.1, Paragraph 3"
        metadata: {
            // Which page number (approximate)
            pageNumber: {
                type: Number,
                default: 1,
            },

            // Which section/chapter heading
            // We detect headings during chunking
            sectionTitle: {
                type: String,
                default: 'General',
            },

            // Which paragraph within the section
            paragraph: {
                type: Number,
            },
        },

        // ── embedding: The vector representation ──
        //
        // Array of 768 floating-point numbers
        // Generated by Google's text-embedding-004 model
        //
        // Example (simplified, actual has 768 numbers):
        // [0.0234, -0.0456, 0.0789, 0.0123, -0.0345, ...]
        //
        // These numbers capture the SEMANTIC MEANING of the text
        // Texts with similar meanings have similar number patterns
        //
        // MongoDB Atlas Vector Search uses these for similarity queries
        embedding: {
            type: [Number],
            required: [true, 'Embedding vector is required'],
        },
    },
    {
        timestamps: true,
    }
);

// ── Compound Index ──
// Makes queries like "find chunk 5 of scheme X" very fast
schemeChunkSchema.index({ schemeId: 1, chunkIndex: 1 });

// ──────────────────────────────────────
// IMPORTANT: VECTOR SEARCH INDEX
//
// For MongoDB Atlas Vector Search to work, you need to
// create a Search Index in MongoDB Atlas UI
//
// Steps:
// 1. Go to MongoDB Atlas → Your Cluster
// 2. Click "Search" tab
// 3. Click "Create Search Index"
// 4. Choose "JSON Editor"
// 5. Select collection: "schemechunks"
// 6. Index name: "vector_index"
// 7. Paste this JSON:
//
// {
//   "fields": [
//     {
//       "type": "vector",
//       "path": "embedding",
//       "numDimensions": 768,
//       "similarity": "cosine"
//     },
//     {
//       "type": "filter",
//       "path": "schemeId"
//     }
//   ]
// }
//
// 8. Click "Create"
//
// WITHOUT THIS INDEX:
// Vector search queries will FAIL
// You'll get: "Index not found" error
//
// ALTERNATIVE (if Atlas Vector Search isn't available):
// We can do manual cosine similarity in code
// (slower but works without the index)
// See the fallback in pdfProcessingService.ts
// ──────────────────────────────────────

const SchemeChunk = mongoose.model<ISchemeChunk>('SchemeChunk', schemeChunkSchema);
export default SchemeChunk;